import player
player.move_forward(2)
player.turn_left()
player.move_forward(3)
player.speak("Hello")
player.turn_left()
player.move_forward(2)
player.turn_right()
player.move_forward(4)
player.speak("Hello")
player.turn_right()
player.move_forward(7)
player.speak("Hello")