import player
player.move_forward(2)
player.turn_right()
player.move_forward(2)
player.turn_left()
player.move_forward(4)
player.turn_left()
player.move_forward(4)
player.turn_left()
player.move_forward(2)